### ISSUE TITLE
Error: XML parse error.

### ISSUE THREAD

**Issue by javierflores87** [mrlesmithjr/cacti#4]
When I try to import Cacti say me "Error: XML parse error."

My Cact version is 0.8.8b

**Comment by mrlesmithjr** [comment]
@javierflores87 Thanks for letting me know this. Looks like I will need to import into `0.8.8b` and then export the templates.

**Comment by mrlesmithjr** [comment]
@javierflores87 Were you able to resolve this issue? I have not had the time to look into this further yet.
