### ISSUE TITLE
NO SNMP Data Returned

### ISSUE THREAD

**Issue by zetoo1412** [mrlesmithjr/cacti#5]
Cant get any data using windows snmp.
Verbouse query failed to pull data.

Any idea why ?

I am using 0.8.8f version.

*All installation steps is done.

**Comment by mrlesmithjr** [comment]
@zetoo1412  Were you able to resolve this issue?

**Comment by zetoo1412** [comment]
Still no idea why I got no snmp data returned by verbous query.
snmpwalk working
