### ISSUE TITLE
Cacti Template for windows servers

### ISSUE THREAD

**Issue by ck-7** [mrlesmithjr/cacti#7]
Hi Larry,
  Shall we get an update on the Windows Server 2016 and 2019 template for the cacti version 1.2.X?

**Comment by mrlesmithjr** [comment]
@ck-7 Unfortunately I haven't used Cacti in years. However, possibly someone would be willing to contribute on this here.

**Comment by mrlesmithjr** [comment]
Also, there would be some benefit here as well. https://github.com/mrlesmithjr/ansible-cacti

**Comment by ck-7** [comment]
> @ck-7 Unfortunately I haven't used Cacti in years. However, possibly someone would be willing to contribute on this here.

No issues Larry. I will try to work myself I will post the templates here.if some one needs
